### ISSUE TITLE
code systems not in VSAC

### ISSUE THREAD

**Issue by p9g** [cqframework/CQL-Formatting-and-Usage-Wiki#17]
https://github.com/cqframework/CQL-Formatting-and-Usage-Wiki/blob/master/Source/Libraries/CumulativeMedicationDuration-1.0.000.cql#L9-L38 

These 2 code systems, and the associated codes, are not in VSAC.
I could not find the code systems using https://vsac.nlm.nih.gov/context/cs

Looking for them using FHIR also comes up empty
curl -s -k -u apiKey:your-key-here https://cts.nlm.nih.gov/fhir/r4/CodeSystem?_format=json^&name=timing  
curl -s -k -u apiKey:your-key-here https://cts.nlm.nih.gov/fhir/r4/CodeSystem?_format=json^&name:contains=timing

Therefore, these codes cannot be added when creating this library in MAT (for QDM); apparently MAT does not verify with VSAC that those code systems exist since a FHIR version is in MAT.

http://tx.fhir.org/r4/CodeSystem?_format=json&name:contains=timing  finds 4 code systems including both urn:oid:2.16.840.1.113883.4.642.4.76 and urn:oid:2.16.840.1.113883.5.139 (with 2 versions of ..5.139)

https://r4.ontoserver.csiro.au/fhir/CodeSystem?_format=json&name:contains=timing finds them

**Comment by p9g** [comment]
Note that https://github.com/cqframework/CQL-Formatting-and-Usage-Wiki/commit/e534abea12b68bc690a6ed75e9a24bf88387f2d1 deleted the 1.0.000 (QDM 5.6) library linked in my original issue above.  This comment was about the QDM verison of CMD; QDM measures in MAT must pull value sets from VSAC, so it was an issue if those value sets were used.  
https://github.com/cqframework/CQL-Formatting-and-Usage-Wiki/commit/09ad8eae31981b5bec1b04172e407e0de6486961 added v 0.1.000 of CMD which uses Direct Referenced Codes (DRC) instead of those value sets.
https://github.com/cqframework/CQL-Formatting-and-Usage-Wiki/blob/master/Source/Cooking%20With%20CQL/57/CumulativeMedicationDuration-0.3.000.cql is newer.
I did not intend this issue to be about FHIR measures and where to find value sets; I probably shoudl have mentioned QDM in the title.

**Comment by p9g** [comment]
Given updates in the QDM CMD library, this can be closed.

**Comment by JSRankins** [comment]
Hi @p9g My comments were in reference to the following: _apparently MAT does not verify with VSAC that those code systems exist since a FHIR version is in MAT._ The community wanted to use code systems that were not in VSAC but that were in FHIR. Hope that helps.

**Comment by p9g** [comment]
Thanks.  I think I didn't realize at the time that MAT allows copy and paste of value sets into CQL Editor and does not check that those value sets are in VSAC. For QDM, MAT does not allow pasting of valuesets (etc) into the CQL editor and as you stated on 27 Aug QDM in MAT only allows code systems to be provide in measures if they are in VSAC.
