### ISSUE TITLE
exists "Has Encounter Treatments"

### ISSUE THREAD

**Issue by p9g** [cqframework/CQL-Formatting-and-Usage-Wiki#9]
https://github.com/esacinc/CQL-Formatting-and-Usage-Wiki/blob/master/Source/Cooking%20With%20CQL/43/38_SingletonExists.cql#L31  

Remove "exists" from this line.

**Comment by brynrhodes** [comment]
Fixed, thank you Paul!

**Comment by p9g** [comment]
Now at https://github.com/cqframework/CQL-Formatting-and-Usage-Wiki/blob/master/Source/Cooking%20With%20CQL/43/38_SingletonExists.cql

fixed in commit 25cbcc8f23bca57d4b29acf4522d730ff0814001
